/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.SystemAdminWorkArea;

import Business.Ecosystem;
import Business.Enterprise.DistributorEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author meetdoshi
 */

public class AddVaccinePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Ecosystem system;
    
    public AddVaccinePanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        vaccineNameLabel = new javax.swing.JLabel();
        diseasesNameLabel = new javax.swing.JLabel();
        vaccineNameTextField = new javax.swing.JTextField();
        diseasesNameTextField = new javax.swing.JTextField();
        addVaccineButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleJLabel.setText("Add Vaccine");
        add(titleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 22, -1, -1));

        vaccineNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vaccineNameLabel.setText("Vaccine Name :");
        add(vaccineNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 92, 140, 40));

        diseasesNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        diseasesNameLabel.setText("Diseases Name :");
        add(diseasesNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 164, 140, 40));

        vaccineNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(vaccineNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 200, 40));

        diseasesNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(diseasesNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 200, 40));

        addVaccineButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addVaccineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OrderVacccine.jpg"))); // NOI18N
        addVaccineButton.setText("Add Vaccine");
        addVaccineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccineButtonActionPerformed(evt);
            }
        });
        add(addVaccineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 241, 230, 50));

        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.jpg"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vaccine Doodle.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, -9, 1220, 1020));
    }// </editor-fold>//GEN-END:initComponents

    private void addVaccineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccineButtonActionPerformed
        try{
            String vaccineName = vaccineNameTextField.getText();
            String diseasesName = diseasesNameTextField.getText();
            Vaccine vaccine = system.getVaccineDirectory().createNewVaccine();
            vaccine.setVaccineName(vaccineName);
            vaccine.setDiseaseName(diseasesName);
            Enterprise ent = null;
            
            for(Network network : system.getNetworkDirectory()){
                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterprisesDirectory()){
                    if(enterprise instanceof DistributorEnterprise){
                        ent = enterprise;
                    }
                }
            }
            Organization o = null;
            for(Organization organization : ent.getOrganizationDirectory().getOrganizationDirectory()){
                if(organization instanceof InventoryOrganization){
                    o = organization;
                }
            }
            o.getInventoryDirectory().createNewInventory(vaccine);
            JOptionPane.showMessageDialog(null, "New Vaccine has been added successfully !!!");
            vaccineNameTextField.setText(null);
            diseasesNameTextField.setText(null);
        }
        catch(Exception e){
            System.out.println("Exception executed" + e);
        }
    }//GEN-LAST:event_addVaccineButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccineButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel diseasesNameLabel;
    private javax.swing.JTextField diseasesNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel vaccineNameLabel;
    private javax.swing.JTextField vaccineNameTextField;
    // End of variables declaration//GEN-END:variables
}
