/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.SystemAdminWorkArea;

import Business.Ecosystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meetdoshi
 */

public class ManageNetworkPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Ecosystem system;
    Pattern p;
    
    public ManageNetworkPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
        populateNetworkTable();
    }
    
    private void populateNetworkTable(){
        DefaultTableModel model = (DefaultTableModel)networkTable.getModel();
        
        model.setRowCount(0);
        for (Network network : system.getNetworkDirectory()){
            Object[] row = new Object[1];
            row[0] = network.getNetworkName();
            model.addRow(row);
        }
    }
    
    public boolean validateName(String name) {
        String nameValidate = "[A-Za-z]{1,100}";
        p = Pattern.compile(nameValidate);
        Matcher matcher = p.matcher(name);
        return matcher.matches();
    }
    
    public boolean validateUsername(String username) {
        String uservalidate = "[a-zA-Z0-9!@_]{4,100}";
        p = Pattern.compile(uservalidate);
        Matcher matcher = p.matcher(username);
        return matcher.matches();
    }
    
    public boolean validatePassword(String password) {
        String passvalidate = "[a-zA-Z0-9!@_*$#%&^()-]{4,100}";
        p = Pattern.compile(passvalidate);
        Matcher matcher = p.matcher(password);
        return matcher.matches();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkTable = new javax.swing.JTable();
        networkNameLabel = new javax.swing.JLabel();
        networkNameTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 29, -1, -1));

        networkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkTable);
        if (networkTable.getColumnModel().getColumnCount() > 0) {
            networkTable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 108, -1, 181));

        networkNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        networkNameLabel.setText("Network Name :");
        add(networkNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        networkNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        networkNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkNameTextFieldActionPerformed(evt);
            }
        });
        add(networkNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 199, -1));

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Submit.jpg"))); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, 40));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.jpg"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 436, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BluePlain-4.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1200, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try{
            String name = networkNameTextField.getText();
            boolean nameCheck = validateName(networkNameTextField.getText().toString());
            
            if(name.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter a network !!!");
            }
            else{
                if (nameCheck){
                    Network network = system.createNetwork(name);
                    JOptionPane.showMessageDialog(submitButton, "Network Added Successfully");
                    populateNetworkTable();
                    networkNameTextField.setText(null);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid Network Name !!!");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check input fields !!!");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void networkNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkNameTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel networkNameLabel;
    private javax.swing.JTextField networkNameTextField;
    private javax.swing.JTable networkTable;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
