/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.SystemAdminWorkArea;

import Business.Ecosystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author meetdoshi
 */

public class SystemAdminPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Ecosystem system;
    private UserAccount userAccount;
    
    public SystemAdminPanel(JPanel userProcessContainer, Ecosystem system, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        manageNetworkJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        manageEnterpriseAdminJButton = new javax.swing.JButton();
        manageVaccineJButton = new javax.swing.JButton();
        manageVaccineOrderJButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(175, 199, 209));

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleJLabel.setText("System Admin ");

        manageNetworkJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageNetworkJButton.setText("Manage Network");
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseAdminJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageEnterpriseAdminJButton.setText("Manage Enterprise Admin");
        manageEnterpriseAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminJButtonActionPerformed(evt);
            }
        });

        manageVaccineJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageVaccineJButton.setText("Manage Vaccine ");
        manageVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVaccineJButtonActionPerformed(evt);
            }
        });

        manageVaccineOrderJButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageVaccineOrderJButton1.setText("Manage Vaccine Order Request ");
        manageVaccineOrderJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVaccineOrderJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addComponent(titleJLabel)
                .addContainerGap(545, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageNetworkJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageVaccineOrderJButton1)
                    .addComponent(manageVaccineJButton)
                    .addComponent(manageEnterpriseAdminJButton)
                    .addComponent(manageEnterpriseJButton))
                .addGap(445, 445, 445))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {manageEnterpriseAdminJButton, manageEnterpriseJButton, manageNetworkJButton, manageVaccineJButton, manageVaccineOrderJButton1});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titleJLabel)
                .addGap(30, 30, 30)
                .addComponent(manageNetworkJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(manageEnterpriseJButton)
                .addGap(39, 39, 39)
                .addComponent(manageEnterpriseAdminJButton)
                .addGap(42, 42, 42)
                .addComponent(manageVaccineOrderJButton1)
                .addGap(32, 32, 32)
                .addComponent(manageVaccineJButton)
                .addContainerGap(533, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {manageEnterpriseAdminJButton, manageEnterpriseJButton, manageNetworkJButton, manageVaccineJButton, manageVaccineOrderJButton1});

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed
        try{
            ManageNetworkPanel manageNetworkPanel = new ManageNetworkPanel(userProcessContainer, system);
            userProcessContainer.add("manageNetworkPanel", manageNetworkPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        catch(Exception e){
            System.out.println("Exception executed" + e);
        }
    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed
        try{
            ManageEnterprisePanel manageEnterprisePanel = new ManageEnterprisePanel(userProcessContainer, system);
            userProcessContainer.add("manageEnterprisePanel", manageEnterprisePanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        catch(Exception e){
            System.out.println("Exception executed" + e);
        }
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void manageEnterpriseAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminJButtonActionPerformed
        try{
            ManageEnterpriseAdminPanel manageEnterpriseAdminPanel = new ManageEnterpriseAdminPanel(userProcessContainer, system);
            userProcessContainer.add("manageEnterpriseAdminPanel", manageEnterpriseAdminPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        catch(Exception e){
            System.out.println("Exception executed" + e);
        }
    }//GEN-LAST:event_manageEnterpriseAdminJButtonActionPerformed

    private void manageVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVaccineJButtonActionPerformed
        try{
            ManageVaccinePanel manageVaccine = new ManageVaccinePanel(userProcessContainer, system);
            userProcessContainer.add("ManageVaccinePanel", manageVaccine);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        catch(Exception e){
            System.out.println("Exception executed" + e);
        }
    }//GEN-LAST:event_manageVaccineJButtonActionPerformed

    private void manageVaccineOrderJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVaccineOrderJButton1ActionPerformed
        try{
            ManageVaccineOrderRequestPanel manageVaccineOrderRequestPanel = new ManageVaccineOrderRequestPanel(userProcessContainer, userAccount, system);
            userProcessContainer.add("ManageVaccineOrderRequestPanel", manageVaccineOrderRequestPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        catch(Exception e){
            System.out.println("Exception executed" + e);
        }
    }//GEN-LAST:event_manageVaccineOrderJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageEnterpriseAdminJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageNetworkJButton;
    private javax.swing.JButton manageVaccineJButton;
    private javax.swing.JButton manageVaccineOrderJButton1;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
