/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProviderWorkArea;

import Business.Enterprise.ProviderEnterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kalindjoshi
 */
public class ManagePharmacyPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ManagePharmacyWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private ProviderEnterprise providerEnterprise;
    
    public ManagePharmacyPanel(JPanel userProcessContainer, ProviderEnterprise providerEnterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.providerEnterprise = providerEnterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageEmployeeButton = new javax.swing.JButton();
        manageUserAccountButton = new javax.swing.JButton();
        addPharmacyButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Pharmacy Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 26, -1, -1));

        manageEmployeeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageEmployeeButton.setText("Manage Pharmacy Employee ");
        manageEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 320, 50));

        manageUserAccountButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageUserAccountButton.setText("Manage Pharmacy UserAccount ");
        manageUserAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountButtonActionPerformed(evt);
            }
        });
        add(manageUserAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 158, 320, 60));

        addPharmacyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addPharmacyButton.setText("Add Pharmacy ");
        addPharmacyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPharmacyButtonActionPerformed(evt);
            }
        });
        add(addPharmacyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 320, 50));

        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.jpg"))); // NOI18N
        backButton.setText(" Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/high-angle-view-white-blue-candy-capsules-green-background_23-2147877557.jpg-2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 5, 1200, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeButtonActionPerformed
        
        ManagePharmacyEmployeePanel manageEmployeePanel = new ManagePharmacyEmployeePanel(userProcessContainer, providerEnterprise);
        userProcessContainer.add("ManagePharmacyEmploeePanel", manageEmployeePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeButtonActionPerformed

    private void manageUserAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountButtonActionPerformed
        
        ManagePharmacyUserAccountPanel manageUserAccountPanel = new ManagePharmacyUserAccountPanel(userProcessContainer, providerEnterprise);
        userProcessContainer.add("ManagePharmacyUserAccountPanel", manageUserAccountPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageUserAccountButtonActionPerformed

    private void addPharmacyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPharmacyButtonActionPerformed
        
        AddPharmacyPanel addPharmacyPanel = new AddPharmacyPanel(userProcessContainer, providerEnterprise);
        userProcessContainer.add("AddPharmacyPanel", addPharmacyPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_addPharmacyButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPharmacyButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageEmployeeButton;
    private javax.swing.JButton manageUserAccountButton;
    // End of variables declaration//GEN-END:variables
}
