/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StateDistributer;

import Business.Ecosystem;
import Business.Enterprise.DistributorEnterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author meetdoshi
 */

public class DistributerFinancePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form DistributerFinanceWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private Ecosystem system;
    private UserAccount userAccount;
    private DistributorEnterprise distributorEnterprise;
    
    public DistributerFinancePanel(JPanel userProcessContainer, Ecosystem system, UserAccount userAccount, DistributorEnterprise distributorEnterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        this.distributorEnterprise = distributorEnterprise;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageManufacturerPaymentButton = new javax.swing.JButton();
        manageProviderPaymentButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Distributor Finance  ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 300, -1));

        manageManufacturerPaymentButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageManufacturerPaymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ManufactureVaccine.jpg"))); // NOI18N
        manageManufacturerPaymentButton.setText("Manage Manufacture Payment ");
        manageManufacturerPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageManufacturerPaymentButtonActionPerformed(evt);
            }
        });
        add(manageManufacturerPaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 310, 70));

        manageProviderPaymentButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageProviderPaymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Payment (3).png"))); // NOI18N
        manageProviderPaymentButton.setText("Manage Provider Payment ");
        manageProviderPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProviderPaymentButtonActionPerformed(evt);
            }
        });
        add(manageProviderPaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 310, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void manageManufacturerPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageManufacturerPaymentButtonActionPerformed
        try{
            ManageManufacturerPaymentPanel manageManufacturerPaymentPanel = new ManageManufacturerPaymentPanel(userProcessContainer, system, userAccount, distributorEnterprise);
            userProcessContainer.add("manageManufacturePaymentPanel", manageManufacturerPaymentPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        catch(Exception e){
            System.out.println("Exception executed" + e);
        }
    }//GEN-LAST:event_manageManufacturerPaymentButtonActionPerformed

    private void manageProviderPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProviderPaymentButtonActionPerformed
        try{
            ManageProviderPaymentPanel manageProviderPaymentPanel = new ManageProviderPaymentPanel(userProcessContainer, system, userAccount, distributorEnterprise);
            userProcessContainer.add("manageProviderPaymentPanel", manageProviderPaymentPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        catch(Exception e){
            System.out.println("Exception executed" + e);
        }
    }//GEN-LAST:event_manageProviderPaymentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageManufacturerPaymentButton;
    private javax.swing.JButton manageProviderPaymentButton;
    // End of variables declaration//GEN-END:variables
}
